Import pandas

In [2]:
import pandas as pd

In [37]:
series = pd.Series([100,200,300])

In [38]:
data = {'a':[100,200,300],'b' :[400,500,600],'c' : [700,800,900]}
df = pd.DataFrame(data)
df

     a    b    c
0  100  400  700
1  200  500  800
2  300  600  900

In [39]:
series.sum()

600

In [41]:
df.sum()

a     600
b    1500
c    2400
dtype: int64

In [40]:
df.sum(axis= "index")

a     600
b    1500
c    2400
dtype: int64

In [36]:
df.sum(axis= "columns")

first      600
second    1500
third     2400
dtype: int64

In [43]:
df.max(axis='index')

a    300
b    600
c    900
dtype: int64

In [4]:
df['a']

0    100
1    200
2    300
Name: a, dtype: int64

In [16]:
df = pd.DataFrame( data = [[100,200,300],[400,500,600],[700,800,900]],
                  index = ['first','second','third'],
                  columns=['a','b','c'])

df

          a    b    c
first   100  200  300
second  400  500  600
third   700  800  900

first     100
second    400
third     700
Name: a, dtype: int64

In [18]:
richest = pd.read_csv("TopRichestInWorld.csv")
richest

,Name,NetWorth,Age,Country/Territory,Source,Industry
0,Elon Musk,"$219,000,000,000",50,United States,"Tesla, SpaceX",Automotive
1,Jeff Bezos,"$171,000,000,000",58,United States,Amazon,Technology
2,Bernard Arnault & family,"$158,000,000,000",73,France,LVMH,Fashion & Retail
3,Bill Gates,"$129,000,000,000",66,United States,Microsoft,Technology
4,Warren Buffett,"$118,000,000,000",91,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...
96,Vladimir Potanin,"$17,300,000,000",61,Russia,metals,Metals & Mining
97,Harold Hamm & family,"$17,200,000,000",76,United States,oil & gas,Energy
98,Sun Piaoyang,"$17,100,000,000",63,China,pharmaceuticals,Healthcare
99,Luo Liguo & family,"$17,000,000,000",66,China,chemicals,Manufacturing
100,Peter Woo,"$17,000,000,000",75,Hong Kong,real estate,Real Estate

In [22]:
richest.shape

(101, 6)

In [21]:
richest.size

606

In [23]:
richest.index

RangeIndex(start=0, stop=101, step=1)

In [24]:
richest.columns

Index(['Name', 'NetWorth', 'Age', 'Country/Territory', 'Source', 'Industry'], dtype='object')

In [25]:
richest.axes

[RangeIndex(start=0, stop=101, step=1),
 Index(['Name', 'NetWorth', 'Age', 'Country/Territory', 'Source', 'Industry'], dtype='object')]

In [26]:
richest.dtypes

Name                 object
NetWorth             object
Age                   int64
Country/Territory    object
Source               object
Industry             object
dtype: object

In [27]:
richest.values

array([['Elon Musk', '$219,000,000,000', 50, 'United States',
        'Tesla, SpaceX', 'Automotive'],
       ['Jeff Bezos', '$171,000,000,000', 58, 'United States', 'Amazon',
        'Technology'],
       ['Bernard Arnault & family', '$158,000,000,000', 73, 'France',
        'LVMH', 'Fashion & Retail'],
       ['Bill Gates', '$129,000,000,000', 66, 'United States',
        'Microsoft', 'Technology'],
       ['Warren Buffett', '$118,000,000,000', 91, 'United States',
        'Berkshire Hathaway', 'Finance & Investments'],
       ['Larry Page', '$111,000,000,000', 49, 'United States', 'Google',
        'Technology'],
       ['Sergey Brin', '$107,000,000,000', 48, 'United States', 'Google',
        'Technology'],
       ['Larry Ellison', '$106,000,000,000', 77, 'United States',
        'software', 'Technology'],
       ['Steve Ballmer', '$91,400,000,000', 66, 'United States',
        'Microsoft', 'Technology'],
       ['Mukesh Ambani', '$90,700,000,000', 64, 'India', 'diversified',
        'Diversified'],
       ['Gautam Adani & family', '$90,000,000,000', 59, 'India',
        'infrastructure, commodities', 'Diversified'],
       ['Michael Bloomberg', '$82,000,000,000', 80, 'United States',
        'Bloomberg LP', 'Media & Entertainment'],
       ['Carlos Slim Helu & family', '$81,200,000,000', 82, 'Mexico',
        'telecom', 'Telecom'],
       ['Francoise Bettencourt Meyers & family', '$74,800,000,000', 68,
        'France', "L'Oréal", 'Fashion & Retail'],
       ['Mark Zuckerberg', '$67,300,000,000', 37, 'United States',
        'Facebook', 'Technology'],
       ['Jim Walton', '$66,200,000,000', 73, 'United States', 'Walmart',
        'Fashion & Retail'],
       ['Zhong Shanshan', '$65,700,000,000', 67, 'China',
        'beverages, pharmaceuticals', 'Food & Beverage'],
       ['Alice Walton', '$65,300,000,000', 72, 'United States',
        'Walmart', 'Fashion & Retail'],
       ['Rob Walton', '$65,000,000,000', 77, 'United States', 'Walmart',
        'Fashion & Retail'],
       ['Changpeng Zhao', '$65,000,000,000', 44, 'Canada',
        'cryptocurrency exchange', 'Finance & Investments'],
       ['Charles Koch', '$60,000,000,000', 86, 'United States',
        'Koch Industries', 'Diversified'],
       ['Julia Koch & family', '$60,000,000,000', 59, 'United States',
        'Koch Industries', 'Diversified'],
       ['Amancio Ortega', '$59,600,000,000', 86, 'Spain', 'Zara',
        'Fashion & Retail'],
       ['Michael Dell', '$55,100,000,000', 57, 'United States',
        'Dell computers', 'Technology'],
       ['Zhang Yiming', '$50,000,000,000', 38, 'China', 'TikTok',
        'Media & Entertainment'],
       ['David Thomson & family', '$49,200,000,000', 64, 'Canada',
        'media', 'Media & Entertainment'],
       ['Phil Knight & family', '$47,300,000,000', 84, 'United States',
        'Nike', 'Fashion & Retail'],
       ['Dieter Schwarz', '$47,100,000,000', 82, 'Germany', 'retail',
        'Fashion & Retail'],
       ['Robin Zeng', '$44,800,000,000', 53, 'Hong Kong', 'batteries',
        'Automotive'],
       ['MacKenzie Scott', '$43,600,000,000', 51, 'United States',
        'Amazon', 'Technology'],
       ['Rodolphe Saadé & family', '$41,400,000,000', 52, 'France',
        'shipping', 'Logistics'],
       ['François Pinault & family', '$40,400,000,000', 85, 'France',
        'luxury goods', 'Fashion & Retail'],
       ['Klaus-Michael Kuehne', '$37,300,000,000', 84, 'Germany',
        'shipping', 'Logistics'],
       ['Ma Huateng', '$37,200,000,000', 50, 'China', 'internet media',
        'Technology'],
       ['Beate Heister & Karl Albrecht Jr. & family', '$36,800,000,000',
        50, 'Germany', 'supermarkets', 'Fashion & Retail'],
       ['Giovanni Ferrero', '$36,200,000,000', 57, 'Italy',
        'Nutella, chocolates', 'Food & Beverage'],
       ['Li Ka-shing', '$34,800,000,000', 93, 'Hong Kong', 'diversified',
        'Diversified'],
       ['Stephen Schwarzman', '$34,800,000,000', 75, 'United States',
        'investments', 'Finance & Investments'],
       ['Lee Shau Kee', '$32,600,000,000', 94, 'Hong Kong',
        'real estate', 'Real Estate'],
       ['Len Blavatnik', '$32,500,000,000', 64, 'United States',
        'music, chemicals', 'Diversified'],
       ['Jacqueline Mars', '$31,700,000,000', 82, 'United States',
        'candy, pet food', 'Food & Beverage'],
       ['John Mars', '$31,700,000,000', 86, 'United States',
        'candy, pet food', 'Food & Beverage'],
       ['Alain Wertheimer', '$31,200,000,000', 73, 'France', 'Chanel',
        'Fashion & Retail'],
       ['Gerard Wertheimer', '$31,200,000,000', 71, 'France', 'Chanel',
        'Fashion & Retail'],
       ['German Larrea Mota Velasco & family', '$30,800,000,000', 68,
        'Mexico', 'mining', 'Metals & Mining'],
       ['Gina Rinehart', '$30,200,000,000', 68, 'Australia', 'mining',
        'Metals & Mining'],
       ['Shiv Nadar', '$28,700,000,000', 76, 'India',
        'software services', 'Technology'],
       ['Jim Simons', '$28,600,000,000', 83, 'United States',
        'hedge funds', 'Finance & Investments'],
       ['He Xiangjian', '$28,300,000,000', 79, 'China',
        'home appliances', 'Manufacturing'],
       ['Miriam Adelson', '$27,500,000,000', 76, 'United States',
        'casinos', 'Gambling & Casinos'],
       ['Dietrich Mateschitz', '$27,400,000,000', 77, 'Austria',
        'Red Bull', 'Food & Beverage'],
       ['Leonardo Del Vecchio & family', '$27,300,000,000', 86, 'Italy',
        'eyeglasses', 'Fashion & Retail'],
       ['Ken Griffin', '$27,200,000,000', 53, 'United States',
        'hedge funds', 'Finance & Investments'],
       ['Tadashi Yanai & family', '$26,100,000,000', 73, 'Japan',
        'fashion retail', 'Fashion & Retail'],
       ['William Lei Ding', '$25,200,000,000', 50, 'China',
        'online games', 'Technology'],
       ['Susanne Klatten', '$24,300,000,000', 59, 'Germany',
        'BMW, pharmaceuticals', 'Automotive'],
       ['Cyrus Poonawalla', '$24,300,000,000', 80, 'India', 'vaccines',
        'Healthcare'],
       ['Wang Wei', '$24,300,000,000', 51, 'China', 'package delivery',
        'Service'],
       ['Qin Yinglin', '$24,100,000,000', 56, 'China', 'pig breeding',
        'Food & Beverage'],
       ['Sam Bankman-Fried', '$24,000,000,000', 30, 'United States',
        'cryptocurrency exchange', 'Finance & Investments'],
       ['Takemitsu Takizaki', '$23,900,000,000', 76, 'Japan', 'sensors',
        'Manufacturing'],
       ['Li Shufu', '$23,700,000,000', 58, 'China', 'automobiles',
        'Automotive'],
       ['Emmanuel Besnier', '$23,500,000,000', 51, 'France', 'cheese',
        'Food & Beverage'],
       ['R. Budi Hartono', '$23,200,000,000', 81, 'Indonesia',
        'banking, tobacco', 'Finance & Investments'],
       ['Leonard Lauder', '$23,100,000,000', 89, 'United States',
        'Estee Lauder', 'Fashion & Retail'],
       ['Guillaume Pousaz', '$23,000,000,000', 40, 'Switzerland',
        'fintech', 'Finance & Investments'],
       ['Iris Fontbona & family', '$22,800,000,000', 79, 'Chile',
        'mining', 'Metals & Mining'],
       ['Jack Ma', '$22,800,000,000', 57, 'China', 'e-commerce',
        'Technology'],
       ['Michael Hartono', '$22,300,000,000', 82, 'Indonesia',
        'banking, tobacco', 'Manufacturing'],
       ['Eric Schmidt', '$22,100,000,000', 66, 'United States', 'Google',
        'Technology'],
       ['Ray Dalio', '$22,000,000,000', 72, 'United States',
        'hedge funds', 'Finance & Investments'],
       ['Daniel Gilbert', '$22,000,000,000', 60, 'United States',
        'Quicken Loans', 'Finance & Investments'],
       ['Thomas Frist, Jr. & family', '$21,800,000,000', 83,
        'United States', 'hospitals', 'Healthcare'],
       ['Masayoshi Son', '$21,300,000,000', 64, 'Japan',
        'internet, telecom', 'Telecom'],
       ['Abigail Johnson', '$21,200,000,000', 60, 'United States',
        'money management', 'Finance & Investments'],
       ['Rupert Murdoch & family', '$20,800,000,000', 91,
        'United States', 'newspapers, TV network',
        'Media & Entertainment'],
       ['Stefan Quandt', '$20,700,000,000', 55, 'Germany', 'BMW',
        'Automotive'],
       ['Jensen Huang', '$20,600,000,000', 59, 'United States',
        'semiconductors', 'Technology'],
       ['Huang Shilin', '$20,300,000,000', 55, 'China', 'batteries',
        'Automotive'],
       ['Thomas Peterffy', '$20,100,000,000', 77, 'United States',
        'discount brokerage', 'Finance & Investments'],
       ['Radhakishan Damani', '$20,000,000,000', 67, 'India',
        'retail, investments', 'Fashion & Retail'],
       ['Pang Kang', '$19,600,000,000', 66, 'China', 'soy sauce',
        'Food & Beverage'],
       ['Wang Chuanfu', '$19,500,000,000', 56, 'China',
        'batteries, automobiles', 'Automotive'],
       ['Reinhold Wuerth & family', '$19,000,000,000', 86, 'Germany',
        'fasteners', 'Manufacturing'],
       ['Theo Albrecht, Jr. & family', '$18,700,000,000', 71, 'Germany',
        "Aldi, Trader Joe's", 'Fashion & Retail'],
       ['Yang Huiyan & family', '$18,700,000,000', 40, 'China',
        'real estate', 'Real Estate'],
       ['Vladimir Lisin', '$18,400,000,000', 65, 'Russia',
        'steel, transport', 'Metals & Mining'],
       ['Fan Hongwei & family', '$18,200,000,000', 55, 'China',
        'petrochemicals', 'Energy'],
       ['Lakshmi Mittal', '$17,900,000,000', 71, 'India', 'steel',
        'Metals & Mining'],
       ['Andrew Forrest', '$17,800,000,000', 60, 'Australia', 'mining',
        'Metals & Mining'],
       ['Jiang Rensheng & family', '$17,700,000,000', 68, 'China',
        'vaccines', 'Healthcare'],
       ['Savitri Jindal & family', '$17,700,000,000', 72, 'India',
        'steel', 'Metals & Mining'],
       ['Wang Wenyin', '$17,700,000,000', 54, 'China',
        'mining, copper products', 'Metals & Mining'],
       ['Li Xiting', '$17,600,000,000', 71, 'Singapore',
        'medical devices', 'Healthcare'],
       ['Stefan Persson', '$17,600,000,000', 74, 'Sweden', 'H&M',
        'Fashion & Retail'],
       ['Steve Cohen', '$17,400,000,000', 65, 'United States',
        'hedge funds', 'Finance & Investments'],
       ['Vladimir Potanin', '$17,300,000,000', 61, 'Russia', 'metals',
        'Metals & Mining'],
       ['Harold Hamm & family', '$17,200,000,000', 76, 'United States',
        'oil & gas', 'Energy'],
       ['Sun Piaoyang', '$17,100,000,000', 63, 'China',
        'pharmaceuticals', 'Healthcare'],
       ['Luo Liguo & family', '$17,000,000,000', 66, 'China',
        'chemicals', 'Manufacturing'],
       ['Peter Woo', '$17,000,000,000', 75, 'Hong Kong', 'real estate',
        'Real Estate']], dtype=object)

Read the `imdb_top_1000.csv` file with the following columns: 

`['Series_Title' ,'IMDB_Rating', 'No_of_Votes', 'Gross', 'Released_Year', 'Genre']`

In [41]:
cols = ['Series_Title' ,'IMDB_Rating', 'No_of_Votes', 'Gross', 'Released_Year', 'Genre']
movies= pd.read_csv('imdb_top_1000.csv' , usecols = cols)
movies

,Series_Title,Released_Year,Genre,IMDB_Rating,No_of_Votes,Gross
0,The Shawshank Redemption,1994,Drama,9.3,2343110,"28,341,469"
1,The Godfather,1972,"Crime, Drama",9.2,1620367,"134,966,411"
2,The Dark Knight,2008,"Action, Crime, Drama",9.0,2303232,"534,858,444"
3,The Godfather: Part II,1974,"Crime, Drama",9.0,1129952,"57,300,000"
4,12 Angry Men,1957,"Crime, Drama",9.0,689845,"4,360,000"
...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,"Comedy, Drama, Romance",7.6,166544,NaN
996,Giant,1956,"Drama, Western",7.6,34075,NaN
997,From Here to Eternity,1953,"Drama, Romance, War",7.6,43374,"30,500,000"
998,Lifeboat,1944,"Drama, War",7.6,26471,NaN
999,The 39 Steps,1935,"Crime, Mystery, Thriller",7.6,51853,NaN

In [6]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   object
 2   Genre          1000 non-null   object
 3   IMDB_Rating    1000 non-null   float64
 4   No_of_Votes    1000 non-null   int64
 5   Gross          831 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 47.0+ KB

In [9]:
movies.describe()

       IMDB_Rating   No_of_Votes
count  1000.000000  1.000000e+03
mean      7.949300  2.736929e+05
std       0.275491  3.273727e+05
min       7.600000  2.508800e+04
25%       7.700000  5.552625e+04
50%       7.900000  1.385485e+05
75%       8.100000  3.741612e+05
max       9.300000  2.343110e+06

In [10]:
movies['Gross'] = movies['Gross'].str.replace(',', '')

In [12]:
movies['Gross'].fillna(0,inplace=True)

In [14]:
movies['Gross'] = movies['Gross'].astype('int64')

In [18]:
movies.describe(percentiles=[.20,.40,.60,.80]).round()

       IMDB_Rating  No_of_Votes        Gross
count       1000.0       1000.0       1000.0
mean           8.0     273693.0   56536878.0
std            0.0     327373.0  103238179.0
min            8.0      25088.0          0.0
20%            8.0      48532.0      83938.0
40%            8.0      91409.0    4164722.0
50%            8.0     138548.0   10702752.0
60%            8.0     203748.0   25554221.0
80%            8.0     462439.0   85388198.0
max            9.0    2343110.0  936662225.0

In [19]:
movies.count()

Series_Title     1000
Released_Year    1000
Genre            1000
IMDB_Rating      1000
No_of_Votes      1000
Gross            1000
dtype: int64

In [22]:
movies.mean(numeric_only=True).round()

IMDB_Rating           8.0
No_of_Votes      273693.0
Gross          56536878.0
dtype: float64

In [23]:
movies.min(numeric_only=True).round()

IMDB_Rating        8.0
No_of_Votes    25088.0
Gross              0.0
dtype: float64

In [24]:
movies.max(numeric_only=True).round()

IMDB_Rating            9.0
No_of_Votes      2343110.0
Gross          936662225.0
dtype: float64

In [25]:
movies.quantile(q=.5,numeric_only=True).round(2)

IMDB_Rating           7.9
No_of_Votes      138548.5
Gross          10702751.5
Name: 0.5, dtype: float64

In [28]:
movies.describe(include='O')

       Series_Title Released_Year  Genre
count          1000          1000   1000
unique          999           100    202
top        Drishyam          2014  Drama
freq              2            32     85

In [31]:
movies.nlargest(n=10,columns=['IMDB_Rating','No_of_Votes'])

,Series_Title,Released_Year,Genre,IMDB_Rating,No_of_Votes,Gross
0,The Shawshank Redemption,1994,Drama,9.3,2343110,28341469
1,The Godfather,1972,"Crime, Drama",9.2,1620367,134966411
2,The Dark Knight,2008,"Action, Crime, Drama",9.0,2303232,534858444
3,The Godfather: Part II,1974,"Crime, Drama",9.0,1129952,57300000
4,12 Angry Men,1957,"Crime, Drama",9.0,689845,4360000
6,Pulp Fiction,1994,"Crime, Drama",8.9,1826188,107928762
5,The Lord of the Rings: The Return of the King,2003,"Action, Adventure, Drama",8.9,1642758,377845905
7,Schindler's List,1993,"Biography, Drama, History",8.9,1213505,96898818
8,Inception,2010,"Action, Adventure, Sci-Fi",8.8,2067042,292576195
9,Fight Club,1999,Drama,8.8,1854740,37030102

In [32]:
movies.nsmallest(n=10,columns=['IMDB_Rating','No_of_Votes']) #keep is used to keep duplicate or not.

,Series_Title,Released_Year,Genre,IMDB_Rating,No_of_Votes,Gross
989,The Long Goodbye,1973,"Comedy, Crime, Drama",7.6,26337,959000
998,Lifeboat,1944,"Drama, War",7.6,26471,0
971,Omohide poro poro,1991,"Animation, Drama, Romance",7.6,27071,453243
981,On Golden Pond,1981,Drama,7.6,27650,119285432
880,Nelyubov,2017,Drama,7.6,29765,566356
990,Giù la testa,1971,"Drama, War, Western",7.6,30144,696690
920,The Secret of Kells,2009,"Animation, Adventure, Family",7.6,31779,686383
984,The Muppet Movie,1979,"Adventure, Comedy, Family",7.6,32802,76657000
986,Watership Down,1978,"Animation, Adventure, Drama",7.6,33656,0
996,Giant,1956,"Drama, Western",7.6,34075,0

In [42]:
movies.set_index('Series_Title', drop=False, inplace =False)

,Series_Title,Released_Year,Genre,IMDB_Rating,No_of_Votes,Gross
Series_Title,,,,,,
The Shawshank Redemption,The Shawshank Redemption,1994,Drama,9.3,2343110,"28,341,469"
The Godfather,The Godfather,1972,"Crime, Drama",9.2,1620367,"134,966,411"
The Dark Knight,The Dark Knight,2008,"Action, Crime, Drama",9.0,2303232,"534,858,444"
The Godfather: Part II,The Godfather: Part II,1974,"Crime, Drama",9.0,1129952,"57,300,000"
12 Angry Men,12 Angry Men,1957,"Crime, Drama",9.0,689845,"4,360,000"
...,...,...,...,...,...,...
Breakfast at Tiffany's,Breakfast at Tiffany's,1961,"Comedy, Drama, Romance",7.6,166544,NaN
Giant,Giant,1956,"Drama, Western",7.6,34075,NaN
From Here to Eternity,From Here to Eternity,1953,"Drama, Romance, War",7.6,43374,"30,500,000"
Lifeboat,Lifeboat,1944,"Drama, War",7.6,26471,NaN
The 39 Steps,The 39 Steps,1935,"Crime, Mystery, Thriller",7.6,51853,NaN

In [44]:
movies.reset_index( drop=True, inplace =False)

,Series_Title,Released_Year,Genre,IMDB_Rating,No_of_Votes,Gross
0,The Shawshank Redemption,1994,Drama,9.3,2343110,"28,341,469"
1,The Godfather,1972,"Crime, Drama",9.2,1620367,"134,966,411"
2,The Dark Knight,2008,"Action, Crime, Drama",9.0,2303232,"534,858,444"
3,The Godfather: Part II,1974,"Crime, Drama",9.0,1129952,"57,300,000"
4,12 Angry Men,1957,"Crime, Drama",9.0,689845,"4,360,000"
...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,"Comedy, Drama, Romance",7.6,166544,NaN
996,Giant,1956,"Drama, Western",7.6,34075,NaN
997,From Here to Eternity,1953,"Drama, Romance, War",7.6,43374,"30,500,000"
998,Lifeboat,1944,"Drama, War",7.6,26471,NaN
999,The 39 Steps,1935,"Crime, Mystery, Thriller",7.6,51853,NaN

In [45]:
movies

,Series_Title,Released_Year,Genre,IMDB_Rating,No_of_Votes,Gross
0,The Shawshank Redemption,1994,Drama,9.3,2343110,"28,341,469"
1,The Godfather,1972,"Crime, Drama",9.2,1620367,"134,966,411"
2,The Dark Knight,2008,"Action, Crime, Drama",9.0,2303232,"534,858,444"
3,The Godfather: Part II,1974,"Crime, Drama",9.0,1129952,"57,300,000"
4,12 Angry Men,1957,"Crime, Drama",9.0,689845,"4,360,000"
...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,"Comedy, Drama, Romance",7.6,166544,NaN
996,Giant,1956,"Drama, Western",7.6,34075,NaN
997,From Here to Eternity,1953,"Drama, Romance, War",7.6,43374,"30,500,000"
998,Lifeboat,1944,"Drama, War",7.6,26471,NaN
999,The 39 Steps,1935,"Crime, Mystery, Thriller",7.6,51853,NaN

Find the lowest scored movie with the lowest amount of votes

In [7]:
movies.nsmallest(n=1 , columns= ['IMDB_Rating','No_of_Votes'])

,Series_Title,Released_Year,Genre,IMDB_Rating,No_of_Votes,Gross
989,The Long Goodbye,1973,"Comedy, Crime, Drama",7.6,26337,"959,000"

Find the highest scored movie with the highest amount of votes

In [9]:
movies.nlargest(n=1 , columns= ['IMDB_Rating','No_of_Votes'])

,Series_Title,Released_Year,Genre,IMDB_Rating,No_of_Votes,Gross
0,The Shawshank Redemption,1994,Drama,9.3,2343110,"28,341,469"

Find the top 5 genres

In [10]:
movies.value_counts('Genre').head(5)

Genre
Drama                     85
Drama, Romance            37
Comedy, Drama             35
Comedy, Drama, Romance    31
Action, Crime, Drama      30
dtype: int64

***Bonus: What are the top 3 grossing movies?***

In [12]:
movies['Gross'] = movies['Gross'].str.replace(',', '')

In [14]:
movies['Gross'].fillna(0,inplace= True)

In [16]:
movies['Gross'] = movies['Gross'].astype('int64')

In [20]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   object
 2   Genre          1000 non-null   object
 3   IMDB_Rating    1000 non-null   float64
 4   No_of_Votes    1000 non-null   int64
 5   Gross          1000 non-null   int64
dtypes: float64(1), int64(2), object(3)
memory usage: 47.0+ KB

In [32]:
movies.nlargest(n=3, columns = 'Gross')

,Series_Title,Released_Year,Genre,IMDB_Rating,No_of_Votes,Gross
477,Star Wars: Episode VII - The Force Awakens,2015,"Action, Adventure, Sci-Fi",7.9,860823,936662225
59,Avengers: Endgame,2019,"Action, Adventure, Drama",8.4,809955,858373000
623,Avatar,2009,"Action, Adventure, Fantasy",7.8,1118998,760507625