### Course HandsOn

In [2]:
import pandas as pd

In [3]:
titanic = pd.read_excel('titanic3.xls', index_col = 'name')
titanic

,pclass,survived,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
name,,,,,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
"Allison, Master. Hudson Trevor",1,1,male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Miss. Helen Loraine",1,0,female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
"Zabour, Miss. Thamine",3,0,female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
"Zakarian, Mr. Ortin",3,0,male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
"Zimmerman, Mr. Leo",3,0,male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [4]:
titanic.sort_index(inplace = True)
titanic

,pclass,survived,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
name,,,,,,,,,,,,,
"Abbing, Mr. Anthony",3,0,male,42.0,0,0,C.A. 5547,7.5500,NaN,S,NaN,NaN,NaN
"Abbott, Master. Eugene Joseph",3,0,male,13.0,0,2,C.A. 2673,20.2500,NaN,S,NaN,NaN,"East Providence, RI"
"Abbott, Mr. Rossmore Edward",3,0,male,16.0,1,1,C.A. 2673,20.2500,NaN,S,NaN,190.0,"East Providence, RI"
"Abbott, Mrs. Stanton (Rosa Hunt)",3,1,female,35.0,1,1,C.A. 2673,20.2500,NaN,S,A,NaN,"East Providence, RI"
"Abelseth, Miss. Karen Marie",3,1,female,16.0,0,0,348125,7.6500,NaN,S,16,NaN,"Norway Los Angeles, CA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",2,1,female,24.0,1,0,SC/PARIS 2167,27.7208,NaN,C,12,NaN,"Lucca, Italy / California"
"van Billiard, Master. James William",3,0,male,NaN,1,1,A/5. 851,14.5000,NaN,S,NaN,NaN,NaN
"van Billiard, Master. Walter John",3,0,male,11.5,1,1,A/5. 851,14.5000,NaN,S,NaN,1.0,NaN
"van Billiard, Mr. Austin Blyler",3,0,male,40.5,0,2,A/5. 851,14.5000,NaN,S,NaN,255.0,NaN
"van Melkebeke, Mr. Philemon",3,0,male,NaN,0,0,345777,9.5000,NaN,S,NaN,NaN,NaN

### loc[]

In [7]:
titanic.loc['Abbott, Mr. Rossmore Edward']

pclass                         3
survived                       0
sex                         male
age                         16.0
sibsp                          1
parch                          1
ticket                 C.A. 2673
fare                       20.25
cabin                        NaN
embarked                       S
boat                         NaN
body                       190.0
home.dest    East Providence, RI
Name: Abbott, Mr. Rossmore Edward, dtype: object

In [8]:
titanic.loc[['Abbott, Mr. Rossmore Edward','van Billiard, Master. James William']]

,pclass,survived,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
name,,,,,,,,,,,,,
"Abbott, Mr. Rossmore Edward",3,0,male,16.0,1,1,C.A. 2673,20.25,NaN,S,NaN,190.0,"East Providence, RI"
"van Billiard, Master. James William",3,0,male,NaN,1,1,A/5. 851,14.50,NaN,S,NaN,NaN,NaN

In [1]:
#titanic.loc['amal']

In [5]:
titanic.loc['Allison, Miss. Helen Loraine','fare']

151.55

In [8]:
titanic.loc['Allison, Miss. Helen Loraine',['fare','sex','age']]

fare    151.55
sex     female
age        2.0
Name: Allison, Miss. Helen Loraine, dtype: object

In [11]:
passengers = ['Abbott, Master. Eugene Joseph','Abbott, Mr. Rossmore Edward']
titanic.loc[passengers, ['fare','sex','age']]

                                fare   sex   age
name
Abbott, Master. Eugene Joseph  20.25  male  13.0
Abbott, Mr. Rossmore Edward    20.25  male  16.0

### iloc[]

In [22]:
import pandas as pd
titanic = pd.read_excel('titanic3.xls', usecols = ['name','sex','age','pclass','fare'])
titanic

,pclass,name,sex,age,fare
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,211.3375
1,1,"Allison, Master. Hudson Trevor",male,0.9167,151.5500
2,1,"Allison, Miss. Helen Loraine",female,2.0000,151.5500
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,151.5500
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,151.5500
...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,14.4542
1305,3,"Zabour, Miss. Thamine",female,NaN,14.4542
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,7.2250
1307,3,"Zakarian, Mr. Ortin",male,27.0000,7.2250
1308,3,"Zimmerman, Mr. Leo",male,29.0000,7.8750

In [20]:
titanic.iloc[0]

pclass           1
sex         female
age           29.0
fare      211.3375
Name: Allen, Miss. Elisabeth Walton, dtype: object

In [21]:
titanic.iloc[0:6]

,pclass,sex,age,fare
name,,,,
"Allen, Miss. Elisabeth Walton",1,female,29.0000,211.3375
"Allison, Master. Hudson Trevor",1,male,0.9167,151.5500
"Allison, Miss. Helen Loraine",1,female,2.0000,151.5500
"Allison, Mr. Hudson Joshua Creighton",1,male,30.0000,151.5500
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,female,25.0000,151.5500
"Anderson, Mr. Harry",1,male,48.0000,26.5500

In [23]:
titanic.iloc[0:6:2]

,pclass,name,sex,age,fare
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,211.3375
2,1,"Allison, Miss. Helen Loraine",female,2.0,151.5500
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,151.5500

In [24]:
titanic.iloc[-3]

pclass                            3
name      Zakarian, Mr. Mapriededer
sex                            male
age                            26.5
fare                          7.225
Name: 1306, dtype: object

In [25]:
titanic.iloc[5,3]

48.0

In [26]:
titanic.iloc[[4,5,6],3]

4    25.0
5    48.0
6    63.0
Name: age, dtype: float64

In [29]:
titanic.iloc[[1,2],[1,2,3,4]]

                             name     sex     age    fare
1  Allison, Master. Hudson Trevor    male  0.9167  151.55
2    Allison, Miss. Helen Loraine  female  2.0000  151.55

In [31]:
titanic.iloc[:,[0,1,2]]

      pclass                                             name     sex
0          1                    Allen, Miss. Elisabeth Walton  female
1          1                   Allison, Master. Hudson Trevor    male
2          1                     Allison, Miss. Helen Loraine  female
3          1             Allison, Mr. Hudson Joshua Creighton    male
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female
...      ...                                              ...     ...
1304       3                             Zabour, Miss. Hileni  female
1305       3                            Zabour, Miss. Thamine  female
1306       3                        Zakarian, Mr. Mapriededer    male
1307       3                              Zakarian, Mr. Ortin    male
1308       3                               Zimmerman, Mr. Leo    male

[1309 rows x 3 columns]

## Broadcasting

Broadcasting is a concept taken from numpy. When we perform an operation with two object og two shapes pandas alligns the object automatiically based on their dimensions and and applies the operations element-wise.

In [1]:
import pandas as pd

A NaN interacts with anything gives a NaN.

In [7]:
df1 = pd.DataFrame(data={'a':[1,2]})
df2 = pd.DataFrame(data = {'a':[10,20],'c':[15,25]})

In [8]:
df1 + df2

    a   c
0  11 NaN
1  22 NaN

In [9]:
titanic = pd.read_excel('titanic3.xls', usecols = ['name','fare','survived'])
titanic

      survived                                             name      fare
0            1                    Allen, Miss. Elisabeth Walton  211.3375
1            1                   Allison, Master. Hudson Trevor  151.5500
2            0                     Allison, Miss. Helen Loraine  151.5500
3            0             Allison, Mr. Hudson Joshua Creighton  151.5500
4            0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  151.5500
...        ...                                              ...       ...
1304         0                             Zabour, Miss. Hileni   14.4542
1305         0                            Zabour, Miss. Thamine   14.4542
1306         0                        Zakarian, Mr. Mapriededer    7.2250
1307         0                              Zakarian, Mr. Ortin    7.2250
1308         0                               Zimmerman, Mr. Leo    7.8750

[1309 rows x 3 columns]

In [10]:
titanic['fare'] / 2

0       105.66875
1        75.77500
2        75.77500
3        75.77500
4        75.77500
          ...
1304      7.22710
1305      7.22710
1306      3.61250
1307      3.61250
1308      3.93750
Name: fare, Length: 1309, dtype: float64

In [11]:
titanic['reduced'] = (titanic['fare'] / 2.).round()
titanic

,survived,name,fare,reduced
0,1,"Allen, Miss. Elisabeth Walton",211.3375,106.0
1,1,"Allison, Master. Hudson Trevor",151.5500,76.0
2,0,"Allison, Miss. Helen Loraine",151.5500,76.0
3,0,"Allison, Mr. Hudson Joshua Creighton",151.5500,76.0
4,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",151.5500,76.0
...,...,...,...,...
1304,0,"Zabour, Miss. Hileni",14.4542,7.0
1305,0,"Zabour, Miss. Thamine",14.4542,7.0
1306,0,"Zakarian, Mr. Mapriededer",7.2250,4.0
1307,0,"Zakarian, Mr. Ortin",7.2250,4.0
1308,0,"Zimmerman, Mr. Leo",7.8750,4.0

### Filtering out data

In [22]:
titanic = pd.read_excel('titanic3.xls', usecols = ['name','sex','age','pclass','fare', 'survived'])
titanic

,pclass,survived,name,sex,age,fare
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,211.3375
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,151.5500
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,151.5500
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,151.5500
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,151.5500
...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,14.4542
1305,3,0,"Zabour, Miss. Thamine",female,NaN,14.4542
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,7.2250
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,7.2250
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,7.8750

In [13]:
titanic['sex']== 'male'

0       False
1        True
2       False
3        True
4       False
        ...
1304    False
1305    False
1306     True
1307     True
1308     True
Name: sex, Length: 1309, dtype: bool

In [14]:
titanic[titanic['sex']== 'male']

      pclass                                  name   sex      age      fare
1          1        Allison, Master. Hudson Trevor  male   0.9167  151.5500
3          1  Allison, Mr. Hudson Joshua Creighton  male  30.0000  151.5500
5          1                   Anderson, Mr. Harry  male  48.0000   26.5500
7          1                Andrews, Mr. Thomas Jr  male  39.0000    0.0000
9          1               Artagaveytia, Mr. Ramon  male  71.0000   49.5042
...      ...                                   ...   ...      ...       ...
1302       3                     Yousif, Mr. Wazli  male      NaN    7.2250
1303       3                 Yousseff, Mr. Gerious  male      NaN   14.4583
1306       3             Zakarian, Mr. Mapriededer  male  26.5000    7.2250
1307       3                   Zakarian, Mr. Ortin  male  27.0000    7.2250
1308       3                    Zimmerman, Mr. Leo  male  29.0000    7.8750

[843 rows x 5 columns]

In [16]:
male_mask = titanic['sex']== 'male'
titanic[male_mask]

      pclass                                  name   sex      age      fare
1          1        Allison, Master. Hudson Trevor  male   0.9167  151.5500
3          1  Allison, Mr. Hudson Joshua Creighton  male  30.0000  151.5500
5          1                   Anderson, Mr. Harry  male  48.0000   26.5500
7          1                Andrews, Mr. Thomas Jr  male  39.0000    0.0000
9          1               Artagaveytia, Mr. Ramon  male  71.0000   49.5042
...      ...                                   ...   ...      ...       ...
1302       3                     Yousif, Mr. Wazli  male      NaN    7.2250
1303       3                 Yousseff, Mr. Gerious  male      NaN   14.4583
1306       3             Zakarian, Mr. Mapriededer  male  26.5000    7.2250
1307       3                   Zakarian, Mr. Ortin  male  27.0000    7.2250
1308       3                    Zimmerman, Mr. Leo  male  29.0000    7.8750

[843 rows x 5 columns]

In [19]:
age_mask = titanic['age'] > 65
titanic[age_mask]

,pclass,name,sex,age,fare
9,1,"Artagaveytia, Mr. Ramon",male,71.0,49.5042
14,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,30.0000
61,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,78.8500
81,1,"Crosby, Capt. Edward Gifford",male,70.0,71.0000
135,1,"Goldschmidt, Mr. George B",male,71.0,34.6542
285,1,"Straus, Mr. Isidor",male,67.0,221.7792
506,2,"Mitchell, Mr. Henry Michael",male,70.0,10.5000
594,2,"Wheadon, Mr. Edward H",male,66.0,10.5000
727,3,"Connors, Mr. Patrick",male,70.5,7.7500
1235,3,"Svensson, Mr. Johan",male,74.0,7.7750

### multiple conditions
& - AND
| - OR
~ - NOT

In [23]:
female_mask = titanic['sex']== 'female'
first_class_mask = titanic['pclass'] == 1
survived_mask = titanic['survived'] == 1
titanic[female_mask & first_class_mask & survived_mask]

,pclass,survived,name,sex,age,fare
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0,211.3375
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,77.9583
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,51.4792
11,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,227.5250
12,1,1,"Aubart, Mme. Leontine Pauline",female,24.0,69.3000
...,...,...,...,...,...,...
311,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,164.8667
314,1,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50.0,211.5000
315,1,1,"Willard, Miss. Constance",female,21.0,26.5500
319,1,1,"Wilson, Miss. Helen Alice",female,31.0,134.5000
322,1,1,"Young, Miss. Marie Grice",female,36.0,135.6333

In [27]:
rich_kids_mask = (titanic['age']<21) & (titanic['fare']> 200)
rich = titanic[rich_kids_mask]

rich.nlargest(5,columns=['age','fare'])

,pclass,survived,name,sex,age,fare
114,1,0,"Fortune, Mr. Charles Alexander",male,19.0,263.0000
250,1,1,"Ryerson, Miss. Emily Borie",female,18.0,262.3750
11,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,227.5250
193,1,1,"Madill, Miss. Georgette Alexandra",female,15.0,211.3375
249,1,1,"Ryerson, Master. John Borie",male,13.0,262.3750

### Between()

In [5]:
import pandas as pd

titanic = pd.read_excel('titanic3.xls', usecols = ['name','sex','age','pclass','fare', 'survived'], index_col= 'name')
titanic

,pclass,survived,sex,age,fare
name,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,211.3375
"Allison, Master. Hudson Trevor",1,1,male,0.9167,151.5500
"Allison, Miss. Helen Loraine",1,0,female,2.0000,151.5500
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,151.5500
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,151.5500
...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,14.4542
"Zabour, Miss. Thamine",3,0,female,NaN,14.4542
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,7.2250
"Zakarian, Mr. Ortin",3,0,male,27.0000,7.2250
"Zimmerman, Mr. Leo",3,0,male,29.0000,7.8750

In [7]:
upper_mask = titanic['age']>=20
lower_mask = titanic['age']<=25

titanic[upper_mask & lower_mask]

,pclass,survived,sex,age,fare
name,,,,,
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0,151.5500
"Aubart, Mme. Leontine Pauline",1,1,female,24.0,69.3000
"Baxter, Mr. Quigg Edmond",1,0,male,24.0,247.5208
"Birnbaum, Mr. Jakob",1,0,male,25.0,26.0000
"Bishop, Mr. Dickinson H",1,1,male,25.0,91.0792
...,...,...,...,...,...
"Vendel, Mr. Olof Edvin",3,0,male,20.0,7.8542
"Vovk, Mr. Janko",3,0,male,22.0,7.8958
"Waelens, Mr. Achille",3,0,male,22.0,9.0000
"Wiklund, Mr. Karl Johan",3,0,male,21.0,6.4958
"Windelov, Mr. Einar",3,0,male,21.0,7.2500

In [10]:
youth_mask = titanic['age'].between(20,25)
titanic[youth_mask]

,pclass,survived,sex,age,fare
name,,,,,
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0,151.5500
"Aubart, Mme. Leontine Pauline",1,1,female,24.0,69.3000
"Baxter, Mr. Quigg Edmond",1,0,male,24.0,247.5208
"Birnbaum, Mr. Jakob",1,0,male,25.0,26.0000
"Bishop, Mr. Dickinson H",1,1,male,25.0,91.0792
...,...,...,...,...,...
"Vendel, Mr. Olof Edvin",3,0,male,20.0,7.8542
"Vovk, Mr. Janko",3,0,male,22.0,7.8958
"Waelens, Mr. Achille",3,0,male,22.0,9.0000
"Wiklund, Mr. Karl Johan",3,0,male,21.0,6.4958
"Windelov, Mr. Einar",3,0,male,21.0,7.2500

In [12]:
youth_mask = titanic['age'].between(20,25, inclusive= 'neither') # can use either both or neither for inclusive
titanic[youth_mask]

,pclass,survived,sex,age,fare
name,,,,,
"Aubart, Mme. Leontine Pauline",1,1,female,24.0,69.3000
"Baxter, Mr. Quigg Edmond",1,0,male,24.0,247.5208
"Bowerman, Miss. Elsie Edith",1,1,female,22.0,55.0000
"Cleaver, Miss. Alice",1,1,female,22.0,151.5500
"Earnshaw, Mrs. Boulton (Olive Potter)",1,1,female,23.0,83.1583
...,...,...,...,...,...
"Vartanian, Mr. David",3,1,male,22.0,7.2250
"Vovk, Mr. Janko",3,0,male,22.0,7.8958
"Waelens, Mr. Achille",3,0,male,22.0,9.0000
"Wiklund, Mr. Karl Johan",3,0,male,21.0,6.4958
"Windelov, Mr. Einar",3,0,male,21.0,7.2500

### isin()

In [13]:
titanic['pclass'].isin([1,2])

name
Allen, Miss. Elisabeth Walton                       True
Allison, Master. Hudson Trevor                      True
Allison, Miss. Helen Loraine                        True
Allison, Mr. Hudson Joshua Creighton                True
Allison, Mrs. Hudson J C (Bessie Waldo Daniels)     True
                                                   ...
Zabour, Miss. Hileni                               False
Zabour, Miss. Thamine                              False
Zakarian, Mr. Mapriededer                          False
Zakarian, Mr. Ortin                                False
Zimmerman, Mr. Leo                                 False
Name: pclass, Length: 1309, dtype: bool

### isnull()

In [14]:
titanic['age'].isnull()

name
Allen, Miss. Elisabeth Walton                      False
Allison, Master. Hudson Trevor                     False
Allison, Miss. Helen Loraine                       False
Allison, Mr. Hudson Joshua Creighton               False
Allison, Mrs. Hudson J C (Bessie Waldo Daniels)    False
                                                   ...
Zabour, Miss. Hileni                               False
Zabour, Miss. Thamine                               True
Zakarian, Mr. Mapriededer                          False
Zakarian, Mr. Ortin                                False
Zimmerman, Mr. Leo                                 False
Name: age, Length: 1309, dtype: bool

### notnull()

In [15]:
titanic['age'].notnull()

name
Allen, Miss. Elisabeth Walton                       True
Allison, Master. Hudson Trevor                      True
Allison, Miss. Helen Loraine                        True
Allison, Mr. Hudson Joshua Creighton                True
Allison, Mrs. Hudson J C (Bessie Waldo Daniels)     True
                                                   ...
Zabour, Miss. Hileni                                True
Zabour, Miss. Thamine                              False
Zakarian, Mr. Mapriededer                           True
Zakarian, Mr. Ortin                                 True
Zimmerman, Mr. Leo                                  True
Name: age, Length: 1309, dtype: bool

### Renaming

In [17]:
titanic.columns

Index(['pclass', 'survived', 'sex', 'age', 'fare'], dtype='object')

In [18]:
titanic.columns[0]

'pclass'

One way to rename is pass a list of same length and always check for index

In [19]:
titanic.columns = ['Class','Survived','Gender','Age','Ticket price']
titanic

,Class,Survived,Gender,Age,Ticket price
name,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,211.3375
"Allison, Master. Hudson Trevor",1,1,male,0.9167,151.5500
"Allison, Miss. Helen Loraine",1,0,female,2.0000,151.5500
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,151.5500
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,151.5500
...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,14.4542
"Zabour, Miss. Thamine",3,0,female,NaN,14.4542
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,7.2250
"Zakarian, Mr. Ortin",3,0,male,27.0000,7.2250
"Zimmerman, Mr. Leo",3,0,male,29.0000,7.8750

In [21]:
titanic.rename(columns = {'Ticket price': 'Fare'})

,Class,Survived,Gender,Age,Fare
name,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,211.3375
"Allison, Master. Hudson Trevor",1,1,male,0.9167,151.5500
"Allison, Miss. Helen Loraine",1,0,female,2.0000,151.5500
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,151.5500
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,151.5500
...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,14.4542
"Zabour, Miss. Thamine",3,0,female,NaN,14.4542
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,7.2250
"Zakarian, Mr. Ortin",3,0,male,27.0000,7.2250
"Zimmerman, Mr. Leo",3,0,male,29.0000,7.8750

In [23]:
titanic.index.name = 'Passengers'
titanic

,Class,Survived,Gender,Age,Ticket price
Passengers,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,211.3375
"Allison, Master. Hudson Trevor",1,1,male,0.9167,151.5500
"Allison, Miss. Helen Loraine",1,0,female,2.0000,151.5500
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,151.5500
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,151.5500
...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,14.4542
"Zabour, Miss. Thamine",3,0,female,NaN,14.4542
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,7.2250
"Zakarian, Mr. Ortin",3,0,male,27.0000,7.2250
"Zimmerman, Mr. Leo",3,0,male,29.0000,7.8750

Import pandas

In [1]:
import pandas as pd

Read the `titanic3.xls` file and set 'name' as the index

In [2]:
titanic = pd.read_excel('titanic3.xls', index_col='name')
titanic

,pclass,survived,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
name,,,,,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
"Allison, Master. Hudson Trevor",1,1,male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Miss. Helen Loraine",1,0,female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
"Zabour, Miss. Thamine",3,0,female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
"Zakarian, Mr. Ortin",3,0,male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
"Zimmerman, Mr. Leo",3,0,male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

Drop the following columns: `['home.dest', 'embarked', 'sibsp', 'parch']`

In [ ]:
titanic.drop(columns=['home.dest', 'embarked', 'sibsp', 'parch'], inplace=True )

In [7]:
titanic

,pclass,survived,sex,age,ticket,fare,cabin,boat,body
name,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,24160,211.3375,B5,2,NaN
"Allison, Master. Hudson Trevor",1,1,male,0.9167,113781,151.5500,C22 C26,11,NaN
"Allison, Miss. Helen Loraine",1,0,female,2.0000,113781,151.5500,C22 C26,NaN,NaN
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,113781,151.5500,C22 C26,NaN,135.0
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,113781,151.5500,C22 C26,NaN,NaN
...,...,...,...,...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,2665,14.4542,NaN,NaN,328.0
"Zabour, Miss. Thamine",3,0,female,NaN,2665,14.4542,NaN,NaN,NaN
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,2656,7.2250,NaN,NaN,304.0
"Zakarian, Mr. Ortin",3,0,male,27.0000,2670,7.2250,NaN,NaN,NaN
"Zimmerman, Mr. Leo",3,0,male,29.0000,315082,7.8750,NaN,NaN,NaN

Filter out all the passengers which did not survive.

In [10]:
alive_mask = titanic['survived'] ==1
titanic = titanic[alive_mask]
titanic

,pclass,survived,sex,age,ticket,fare,cabin,boat,body
name,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,24160,211.3375,B5,2,NaN
"Allison, Master. Hudson Trevor",1,1,male,0.9167,113781,151.5500,C22 C26,11,NaN
"Anderson, Mr. Harry",1,1,male,48.0000,19952,26.5500,E12,3,NaN
"Andrews, Miss. Kornelia Theodosia",1,1,female,63.0000,13502,77.9583,D7,10,NaN
"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,1,female,53.0000,11769,51.4792,C101,D,NaN
...,...,...,...,...,...,...,...,...,...
"Turkula, Mrs. (Hedwig)",3,1,female,63.0000,4134,9.5875,NaN,15,NaN
"Vartanian, Mr. David",3,1,male,22.0000,2658,7.2250,NaN,13 15,NaN
"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",3,1,female,38.0000,2688,7.2292,NaN,C,NaN
"Wilkes, Mrs. James (Ellen Needs)",3,1,female,47.0000,363272,7.0000,NaN,NaN,NaN
"Yasbeck, Mrs. Antoni (Selini Alexander)",3,1,female,15.0000,2659,14.4542,NaN,NaN,NaN

Considering that the **body** column is only used for passengers who did not survive, drop that column, and then do the same thing for the **survived** column.

In [12]:
titanic.drop(columns=['body','survived'], inplace = True)
titanic

,pclass,sex,age,ticket,fare,cabin,boat
name,,,,,,,
"Allen, Miss. Elisabeth Walton",1,female,29.0000,24160,211.3375,B5,2
"Allison, Master. Hudson Trevor",1,male,0.9167,113781,151.5500,C22 C26,11
"Anderson, Mr. Harry",1,male,48.0000,19952,26.5500,E12,3
"Andrews, Miss. Kornelia Theodosia",1,female,63.0000,13502,77.9583,D7,10
"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,female,53.0000,11769,51.4792,C101,D
...,...,...,...,...,...,...,...
"Turkula, Mrs. (Hedwig)",3,female,63.0000,4134,9.5875,NaN,15
"Vartanian, Mr. David",3,male,22.0000,2658,7.2250,NaN,13 15
"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",3,female,38.0000,2688,7.2292,NaN,C
"Wilkes, Mrs. James (Ellen Needs)",3,female,47.0000,363272,7.0000,NaN,NaN
"Yasbeck, Mrs. Antoni (Selini Alexander)",3,female,15.0000,2659,14.4542,NaN,NaN

What is the max **fare** in **3rd class**?

In [13]:
class_mask = titanic['pclass'] == 3

titanic.loc[class_mask,'fare'].max()

56.4958

Rename the index name of 'name' to 'Passenger'

In [14]:
titanic.index.name = 'Passenger'

**BONUS**

Create a new column that's called "Free Coffee", insert 1 if a passenger is either in 1st or 2nd class, otherwise insert 0

In [15]:
coffee_mask = titanic['pclass'].isin([1,2])
titanic['Free Coffee'] = 0

titanic.loc[coffee_mask,'Free Coffee'] = 1

titanic

,pclass,sex,age,ticket,fare,cabin,boat,Free Coffee
Passenger,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,female,29.0000,24160,211.3375,B5,2,1
"Allison, Master. Hudson Trevor",1,male,0.9167,113781,151.5500,C22 C26,11,1
"Anderson, Mr. Harry",1,male,48.0000,19952,26.5500,E12,3,1
"Andrews, Miss. Kornelia Theodosia",1,female,63.0000,13502,77.9583,D7,10,1
"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,female,53.0000,11769,51.4792,C101,D,1
...,...,...,...,...,...,...,...,...
"Turkula, Mrs. (Hedwig)",3,female,63.0000,4134,9.5875,NaN,15,0
"Vartanian, Mr. David",3,male,22.0000,2658,7.2250,NaN,13 15,0
"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",3,female,38.0000,2688,7.2292,NaN,C,0
"Wilkes, Mrs. James (Ellen Needs)",3,female,47.0000,363272,7.0000,NaN,NaN,0
"Yasbeck, Mrs. Antoni (Selini Alexander)",3,female,15.0000,2659,14.4542,NaN,NaN,0

Use value_counts() to verify that 3rd class doesn't get any free coffee

In [16]:
titanic.loc[:,['Free Coffee', 'pclass']].value_counts()

Free Coffee  pclass
1            1         200
0            3         181
1            2         119
dtype: int64